# Generated by Django 2.1.7 on 2020-01-07 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='altkategoriler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altkategoriAdi', models.CharField(max_length=250, verbose_name='Alt Kategori Adı')),
                ('kategoriIcon', models.CharField(max_length=250, verbose_name='Alt Kategori Icon')),
            ],
        ),
        migrations.CreateModel(
            name='cevaplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hikayeCevapMetni', models.TextField(verbose_name='Hikaye Devam Metni')),
                ('hikayeCevapTarih', models.DateField(verbose_name='Hikaye Devam Metni Yayın Tarihi')),
                ('hikayeDurum', models.CharField(max_length=50, verbose_name='Hikaye Devam Metni Yayın Durumu')),
            ],
        ),
        migrations.CreateModel(
            name='hikayeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hikayeAdi', models.CharField(max_length=250, verbose_name='Hikaye Adı')),
                ('hikayeOzet', models.TextField(verbose_name='Hikaye Özeti')),
                ('hikayeMetni', models.TextField(verbose_name='Hikaye Metni')),
                ('hikayeGorsel', models.ImageField(upload_to='', verbose_name='Hikaye Görseli')),
                ('hikayeTarih', models.DateField(verbose_name='Hikaye Yayın Tarihi')),
                ('hikayeDurum', models.CharField(max_length=50, verbose_name='Hikaye Yayın Durumu')),
                ('altkategoriId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitmeyenHikayeApp.altkategoriler', verbose_name='Alt Kategori Adı')),
            ],
        ),
        migrations.CreateModel(
            name='kategoriler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoriAdi', models.CharField(max_length=250, verbose_name='Kategori Adı')),
                ('kategoriIcon', models.CharField(max_length=250, verbose_name='Kategori Icon')),
            ],
        ),
        migrations.AddField(
            model_name='hikayeler',
            name='anakategoriId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitmeyenHikayeApp.kategoriler', verbose_name='Ana Kategori Adı'),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='hikayeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitmeyenHikayeApp.hikayeler', verbose_name='Hikaye Adı'),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='uyeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Hikaye Adı'),
        ),
        migrations.AddField(
            model_name='altkategoriler',
            name='anakategoriId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitmeyenHikayeApp.kategoriler', verbose_name='Ana Kategori Adı'),
        ),
    ]
