# Generated by Django 2.1.7 on 2020-01-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitmeyenHikayeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altkategoriler',
            name='anakategoriId',
        ),
        migrations.RemoveField(
            model_name='hikayeler',
            name='altkategoriId',
        ),
        migrations.DeleteModel(
            name='altkategoriler',
        ),
    ]
