# Generated by Django 2.1.7 on 2020-01-09 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitmeyenHikayeApp', '0003_auto_20200107_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cevaplar',
            name='hit',
            field=models.TextField(blank=True, default=0, null=True, verbose_name='Hit'),
        ),
        migrations.AddField(
            model_name='hikayeler',
            name='hit',
            field=models.TextField(blank=True, default=0, null=True, verbose_name='Hit'),
        ),
        migrations.AlterField(
            model_name='cevaplar',
            name='uyeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Üye Adı'),
        ),
    ]
