# Generated by Django 2.1.7 on 2020-01-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitmeyenHikayeApp', '0004_auto_20200109_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevaplar',
            name='hit',
            field=models.CharField(blank=True, default=0, max_length=250, null=True, verbose_name='Hit'),
        ),
        migrations.AlterField(
            model_name='hikayeler',
            name='hit',
            field=models.CharField(blank=True, default=0, max_length=250, null=True, verbose_name='Hit'),
        ),
    ]
