# Generated by Django 2.1.7 on 2020-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitmeyenHikayeApp', '0005_auto_20200109_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikayeler',
            name='hikayeDurum',
            field=models.CharField(choices=[('0', 'Yanınlanmamış'), ('1', 'Yayınlanmış')], default=1, max_length=50, verbose_name='Hikaye Yayın Durumu'),
        ),
    ]
