# Generated by Django 2.1.7 on 2020-01-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitmeyenHikayeApp', '0006_auto_20200109_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevaplar',
            name='hikayeDurum',
            field=models.CharField(choices=[('0', 'Yanınlanmamış'), ('1', 'Yayınlanmış')], default=0, max_length=50, verbose_name='Hikaye Devam Metni Yayın Durumu'),
        ),
    ]
